import React from 'react';
import firestore from '@react-native-firebase/firestore';
import {View, Text, StyleSheet, Pressable} from 'react-native';

function Home() {
  const onSubmit = async () => {
    try {
      const data = {
        title: '5K 완주를 위한 9주 프로그램',
        program: [
          {
            day: 1,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 2,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 3,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 4,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 5,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 6,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 7,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 8,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 9,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 10,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 11,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 12,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 13,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 14,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 15,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 16,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 17,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 18,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 19,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 20,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 21,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 22,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 23,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 24,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 25,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 26,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 27,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 28,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 29,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 30,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 31,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 32,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 33,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 34,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 35,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 36,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 37,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 38,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 39,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 40,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 41,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 42,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 43,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 44,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 45,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 46,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 47,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 48,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 49,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 50,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 51,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 52,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 53,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 54,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 55,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 56,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 57,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 58,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 59,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 60,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 61,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 62,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
          {
            day: 63,
            content: '',
            exPoint: 0,
            isComplete: false,
            time: 0,
            distance: 0,
          },
        ]
      }
      await firestore().collection('Trainings').add(data);
    } catch (e) {
      console.log(e);
    }
  }

  return (
    <View style={styles.container}>
      <Text>페이지 준비중입니다.</Text>
      <Pressable onPress={onSubmit}>
        <Text style={styles.btn}>등록하기</Text>
      </Pressable>
    </View>
  )
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  btn: {
    color: 'white'
  }
});

export default Home;